version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    networks:
      - backend
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "MyPass@word"
      MSSQL_USER: "sa" 
    ports:
      - "1433:1433"
  sunday_test_api:
    image: ${DOCKER_REGISTRY-}sundaytestapi
    depends_on:
      - mssql
    networks:
      - backend
    build:
      context: .
      dockerfile: Sunday_Test_API/Dockerfile
    environment:
      DbServer: "mssql"
      DbPort: "1433"
      DbUser: "sa"
      Password: "MyPass@word"
      Database: "SundayDb"
    ports:
      - "8090:80"

networks:
  backend:
    driver: bridge
  frontend:
    driver: none

